api_platform:
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources']
    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
#        csv:      ['text/csv']
        html:     ['text/html']
