RMN\ProductBundle\Entity\Brand:
  type: entity
  table: brands
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    description:
      type: string
      length: 255
      nullable: true
  OneToMany:
    products:
      targetEntity: RMN\ProductBundle\Entity\Product
      mappedBy: brand

