RMN\ProductBundle\Entity\Product:
  type: entity
  table: products
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    sku:
      type: string
      length: 255
    description:
      type: string
      length: 255
      nullable: true
    active:
      type: boolean
      column: is_active
  manyToOne:
    brand:
      targetEntity: RMN\ProductBundle\Entity\Brand
      inversedBy: products
      joinColumn:
        name: brand_id
        referencedColumnName: id

